DROP TABLE IF EXISTS challenges CASCADE;
CREATE TABLE challenges (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE,
  genre VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT NOW(),
  max_occupancy INTEGER NOT NULL DEFAULT 2
);
